### ISSUE TITLE
run the code with error: unordered_map file not found

### ISSUE THREAD

**Issue by zuodd** [thehackerati/THVideoFaceSwapper#9]
HI:  how can i solve the problem?
<img width="339" alt="3a48f931-3181-4012-b242-7a30043d245b" src="https://cloud.githubusercontent.com/assets/13743405/9809147/66c3770e-5898-11e5-8384-43641e9c1028.png">

**Comment by zuodd** [comment]
anyone can help me please?  I could not set up the code. the error was upside the image. 
Is any one has the same problem with me? how you got solved? please help.

**Comment by sidan5** [comment]
+1

**Comment by MenLonII** [comment]
+1

**Comment by MenLonII** [comment]
About this problem, your problem is solved?   @zuodd

**Comment by cjrieck** [comment]
Hey guys,

Sorry for the long wait. The project had to be updated using the openFrameworks app generator. I pushed a change to `master` with the updated settings. Let me know how it works for you!

**Comment by MenLonII** [comment]
@cjrieck Thank for your tip ,It works now for me

**Comment by tiepnv2508** [comment]
Hello @MenLonII  & @cjrieck , how to make it work, when i build, it still show error: unordered_map file not found. I downloaded latest THVideoFaceSwapper.zip, extract to THVideoFaceSwapper folder, and i copy THVideoFaceSwapper folder to openFrameworks/apps/myApps/
